apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: semantic-test
  namespace: spark-jobs
spec:
  type: Python
  mode: cluster
  image: data-pipeline-spark:3.5.3
  imagePullPolicy: IfNotPresent
  mainApplicationFile: local:///app/semantic_test.py
  sparkVersion: "3.5.3"
  sparkConf:
    spark.hadoop.fs.s3a.access.key: minio
    spark.hadoop.fs.s3a.secret.key: minio123
    spark.executorEnv.AWS_ACCESS_KEY_ID: minio
    spark.executorEnv.AWS_SECRET_ACCESS_KEY: minio123
    spark.executorEnv.PYTHONPATH: /opt/data-pipeline/python:/app
    spark.kubernetes.driverEnv.AWS_ACCESS_KEY_ID: minio
    spark.kubernetes.driverEnv.AWS_SECRET_ACCESS_KEY: minio123
    spark.kubernetes.driverEnv.PYTHONPATH: /opt/data-pipeline/python:/app
  restartPolicy:
    type: Never
  volumes:
    - name: semantic-test-script
      configMap:
        name: semantic-test-script
        defaultMode: 0555
    - name: minio-tenant-env
      secret:
        secretName: myminio-env-configuration
  driver:
    cores: 1
    memory: 1g
    labels:
      version: 3.5.3
    serviceAccount: spark-operator-spark
    env:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: myminio-env-configuration
            key: AWS_ACCESS_KEY_ID
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: myminio-env-configuration
            key: AWS_SECRET_ACCESS_KEY
      - name: PYTHONPATH
        value: /opt/data-pipeline/python:/app
    volumeMounts:
      - name: semantic-test-script
        mountPath: /app/semantic_test.py
        subPath: semantic_test.py
      - name: semantic-test-script
        mountPath: /app/minio_s3.py
        subPath: minio_s3.py
      - name: semantic-test-script
        mountPath: /app/semantic_uc.py
        subPath: semantic_uc.py
      - name: minio-tenant-env
        mountPath: /var/run/minio-tenant/config.env
        subPath: config.env
        readOnly: true
  executor:
    cores: 1
    instances: 1
    memory: 1g
    labels:
      version: 3.5.3
    env:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: myminio-env-configuration
            key: AWS_ACCESS_KEY_ID
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: myminio-env-configuration
            key: AWS_SECRET_ACCESS_KEY
      - name: PYTHONPATH
        value: /opt/data-pipeline/python:/app
    volumeMounts:
      - name: semantic-test-script
        mountPath: /app/semantic_test.py
        subPath: semantic_test.py
      - name: semantic-test-script
        mountPath: /app/minio_s3.py
        subPath: minio_s3.py
      - name: semantic-test-script
        mountPath: /app/semantic_uc.py
        subPath: semantic_uc.py
      - name: minio-tenant-env
        mountPath: /var/run/minio-tenant/config.env
        subPath: config.env
        readOnly: true
