apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: semantic-test
  namespace: spark-jobs
spec:
  type: Python
  mode: cluster
  image: data-pipeline-spark:3.5.3
  imagePullPolicy: IfNotPresent
  mainApplicationFile: local:///app/semantic_test.py
  deps:
    pyFiles:
      - local:///opt/data-pipeline/semantic_mapper_client.zip
  sparkVersion: "3.5.3"
  restartPolicy:
    type: Never
  volumes:
    - name: semantic-test-script
      configMap:
        name: semantic-test-script
        defaultMode: 0555
    - name: minio-tenant-env
      secret:
        secretName: myminio-env-configuration
  driver:
    cores: 1
    memory: 1g
    labels:
      version: 3.5.3
    serviceAccount: spark-operator-spark
    volumeMounts:
      - name: semantic-test-script
        mountPath: /app
        readOnly: true
      - name: minio-tenant-env
        mountPath: /var/run/minio-tenant/config.env
        subPath: config.env
        readOnly: true
  executor:
    cores: 1
    instances: 1
    memory: 1g
    labels:
      version: 3.5.3
    volumeMounts:
      - name: semantic-test-script
        mountPath: /app
        readOnly: true
      - name: minio-tenant-env
        mountPath: /var/run/minio-tenant/config.env
        subPath: config.env
        readOnly: true
