apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fuseki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "25"
spec:
  project: data-pipeline
  source:
    repoURL: https://github.com/fabian-amrc/data-pipeline-application.git
    targetRevision: main
    path: fuseki
  destination:
    server: https://kubernetes.default.svc
    namespace: fuseki
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
