apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: semantic
resources:
  - manifests/namespace.yaml
  - manifests/pvc.yaml
  - manifests/deployment.yaml
  - manifests/service.yaml

configMapGenerator:
  - name: fuseki-config
    files:
      - config.ttl=config/config.ttl

generatorOptions:
  disableNameSuffixHash: true
