apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: unitycatalog
    releaseName: unity-catalog
    namespace: unity-catalog
    valuesFile: values.yaml
    includeCRDs: true
resources:
  - manifests
patches:
  - path: patches/server-init-command.yaml
