apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-tenant
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: data-pipeline
  destination:
    server: https://kubernetes.default.svc
    namespace: minio-tenant
  source:
    repoURL: https://github.com/fabian-amrc/data-pipeline-application.git
    targetRevision: main
    path: minio/tenant
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
