tenant:
  name: data-pipeline
  configSecret:
    name: myminio-env-configuration
    accessKey: minio
    secretKey: minio123
  pools:
    - servers: 1
      name: pool-0
      volumesPerServer: 4
      size: 10Gi
  certificate:
    requestAutoCert: false

ingress:
  api:
    enabled: false
  console:
    enabled: false
