apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: spark-jobs
resources:
  - applications/spark-pi/spark-pi-sparkapplication.yaml
  - applications/delta-test/delta-test-sparkapplication.yaml
  - applications/semantic-test/semantic-test-sparkapplication.yaml
  - applications/uc-smoke-test/uc-smoke-test-sparkapplication.yaml
configMapGenerator:
  - name: delta-test-script
    files:
      - delta_test.py=applications/delta-test/delta_test.py
      - minio_s3.py=lib/minio_s3.py
  - name: semantic-test-script
    files:
      - semantic_test.py=applications/semantic-test/semantic_test.py
      - minio_s3.py=lib/minio_s3.py
      - semantic_uc.py=applications/semantic-test/semantic_uc.py
  - name: uc-smoke-test-script
    files:
      - uc_smoke_test.py=applications/uc-smoke-test/uc_smoke_test.py
generatorOptions:
  disableNameSuffixHash: true
