apiVersion: v1
kind: Service
metadata:
  name: rdf-graph-explorer
  labels:
    app.kubernetes.io/name: rdf-graph-explorer
    app.kubernetes.io/part-of: semantic-layer
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: rdf-graph-explorer
  ports:
    - name: http
      port: 80
      targetPort: http
