apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: data-pipeline
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  sources:
    - repoURL: https://traefik.github.io/charts
      chart: traefik
      targetRevision: 40.2.0
      helm:
        releaseName: traefik
        valueFiles:
          - $values/traefik/values.yaml
    - repoURL: https://github.com/fabian-amrc/data-pipeline-application.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
