deployment:
  replicas: 1

service:
  type: LoadBalancer

ingressClass:
  enabled: true
  isDefaultClass: true

providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true

ports:
  web:
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    http:
      tls:
        enabled: true
api:
  dashboard: true
ingressRoute:
  dashboard:
    enabled: true
    entryPoints:
      - websecure
