deployment:
  replicas: 1

service:
  spec:
    type: ClusterIP

ingressClass:
  enabled: true
  isDefaultClass: true

providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true

ports:
  web:
    hostPort: 80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    hostPort: 443
    http:
      tls:
        enabled: true
api:
  dashboard: true
ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.local`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
    entryPoints:
      - websecure
