apiVersion: v1
kind: Service
metadata:
  name: ontodia
  labels:
    app.kubernetes.io/name: ontodia
    app.kubernetes.io/part-of: semantic-layer
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ontodia
  ports:
    - name: http
      port: 80
      targetPort: http
