apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: data-pipeline
  destination:
    server: https://kubernetes.default.svc
    namespace: spark-operator
  source:
    repoURL: https://github.com/fabian-amrc/data-pipeline-application.git
    targetRevision: main
    path: spark/operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
