apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: spark-operator
    repo: https://kubeflow.github.io/spark-operator
    version: 2.5.0
    releaseName: spark-operator
    namespace: spark-operator
    valuesFile: values.yaml
    includeCRDs: true
