apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: spark-jobs
resources:
  - jobs/spark-pi-sparkapplication.yaml
  - jobs/uc-smoke-test-sparkapplication.yaml
configMapGenerator:
  - name: uc-smoke-test-script
    files:
      - uc_smoke_test.py=jobs/uc_smoke_test.py
generatorOptions:
  disableNameSuffixHash: true
