apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: semantic-mapper
resources:
  - manifests/namespace.yaml
  - manifests/deployment.yaml
  - manifests/service.yaml
  - manifests/pvc.yaml
  - manifests/fuseki-admin-secret.yaml

generatorOptions:
  disableNameSuffixHash: true
