apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: delta-test
  namespace: spark-jobs
spec:
  type: Python
  mode: cluster
  image: data-pipeline-spark:3.5.3
  imagePullPolicy: IfNotPresent
  mainApplicationFile: local:///app/delta_test.py
  sparkVersion: "3.5.3"
  sparkConf:
    spark.delta.logStore.class: org.apache.spark.sql.delta.storage.S3SingleDriverLogStore
    spark.hadoop.fs.s3a.impl: org.apache.hadoop.fs.s3a.S3AFileSystem
    spark.hadoop.fs.s3a.endpoint: http://data-pipeline-hl.minio-tenant.svc.cluster.local:9000
    spark.hadoop.fs.s3a.path.style.access: "true"
    spark.hadoop.fs.s3a.connection.ssl.enabled: "false"
    spark.hadoop.fs.s3a.aws.credentials.provider: org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
  restartPolicy:
    type: Never
  volumes:
    - name: delta-test-script
      configMap:
        name: delta-test-script
        defaultMode: 0555
    - name: minio-tenant-env
      secret:
        secretName: myminio-env-configuration
  driver:
    cores: 1
    memory: 1g
    labels:
      version: 3.5.3
    serviceAccount: spark-operator-spark
    env:
      - name: MINIO_ENDPOINT
        value: http://data-pipeline-hl.minio-tenant.svc.cluster.local:9000
      - name: OUTPUT_PATH
        value: s3a://delta/delta-test
      - name: MINIO_CONFIG_ENV_FILE
        value: /var/run/minio-tenant/config.env
    volumeMounts:
      - name: delta-test-script
        mountPath: /app/delta_test.py
        subPath: delta_test.py
      - name: minio-tenant-env
        mountPath: /var/run/minio-tenant/config.env
        subPath: config.env
        readOnly: true
  executor:
    cores: 1
    instances: 1
    memory: 1g
    labels:
      version: 3.5.3
    env:
      - name: MINIO_ENDPOINT
        value: http://data-pipeline-hl.minio-tenant.svc.cluster.local:9000
      - name: OUTPUT_PATH
        value: s3a://delta/delta-test
      - name: MINIO_CONFIG_ENV_FILE
        value: /var/run/minio-tenant/config.env
    volumeMounts:
      - name: delta-test-script
        mountPath: /app/delta_test.py
        subPath: delta_test.py
      - name: minio-tenant-env
        mountPath: /var/run/minio-tenant/config.env
        subPath: config.env
        readOnly: true
