apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: delta-test
  namespace: spark-jobs
spec:
  type: Python
  mode: cluster
  image: data-pipeline-spark:3.5.3
  imagePullPolicy: IfNotPresent
  mainApplicationFile: local:///app/delta_test.py
  sparkVersion: "3.5.3"
  restartPolicy:
    type: Never
  volumes:
    - name: delta-test-script
      configMap:
        name: delta-test-script
        defaultMode: 0555
    - name: minio-tenant-env
      secret:
        secretName: myminio-env-configuration
  driver:
    cores: 1
    memory: 1g
    labels:
      version: 3.5.3
    serviceAccount: spark-operator-spark
    env:
      - name: OUTPUT_PATH
        value: s3a://delta/delta-test
    volumeMounts:
      - name: delta-test-script
        mountPath: /app/delta_test.py
        subPath: delta_test.py
      - name: delta-test-script
        mountPath: /app/minio_s3.py
        subPath: minio_s3.py
      - name: minio-tenant-env
        mountPath: /var/run/minio-tenant/config.env
        subPath: config.env
        readOnly: true
  executor:
    cores: 1
    instances: 1
    memory: 1g
    labels:
      version: 3.5.3
    env:
      - name: OUTPUT_PATH
        value: s3a://delta/delta-test
    volumeMounts:
      - name: delta-test-script
        mountPath: /app/delta_test.py
        subPath: delta_test.py
      - name: delta-test-script
        mountPath: /app/minio_s3.py
        subPath: minio_s3.py
      - name: minio-tenant-env
        mountPath: /var/run/minio-tenant/config.env
        subPath: config.env
        readOnly: true
