spark.jars.ivy /tmp/.ivy2

spark.sql.extensions io.delta.sql.DeltaSparkSessionExtension
spark.sql.catalog.spark_catalog org.apache.spark.sql.delta.catalog.DeltaCatalog
spark.sql.catalog.unity io.unitycatalog.spark.UCSingleCatalog
spark.sql.catalog.unity.uri http://unity-catalog-unitycatalog-server.unity-catalog.svc.cluster.local:8080
spark.sql.catalog.unity.token 
spark.sql.defaultCatalog unity

spark.driver.extraJavaOptions -Duser.name=spark
spark.executor.extraJavaOptions -Duser.name=spark
spark.executorEnv.HADOOP_USER_NAME spark
spark.executorEnv.USER spark
spark.executorEnv.LOGNAME spark
spark.executorEnv.AWS_REGION us-east-1
spark.executorEnv.AWS_DEFAULT_REGION us-east-1
spark.executorEnv.MINIO_ENDPOINT http://data-pipeline-hl.minio-tenant.svc.cluster.local:9000

spark.delta.logStore.class org.apache.spark.sql.delta.storage.S3SingleDriverLogStore

spark.hadoop.fs.s3a.impl org.apache.hadoop.fs.s3a.S3AFileSystem
spark.hadoop.fs.s3a.endpoint http://data-pipeline-hl.minio-tenant.svc.cluster.local:9000
spark.hadoop.fs.s3a.path.style.access true
spark.hadoop.fs.s3a.connection.ssl.enabled false
spark.hadoop.fs.s3a.aws.credentials.provider com.amazonaws.auth.EnvironmentVariableCredentialsProvider
