apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: data-pipeline
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 9.5.15
      helm:
        releaseName: argo-cd
        valueFiles:
          - $values/argo/values.yaml
    - repoURL: https://github.com/fabian-amrc/data-pipeline-application.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
