global:
  domain: argocd.local

configs:
  cm:
    kustomize.buildOptions: --enable-helm
  params:
    server.insecure: true

server:
  service:
    type: ClusterIP
  ingress:
    enabled: false

controller:
  replicas: 1

repoServer:
  replicas: 1

applicationSet:
  replicas: 1
