apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-ingressroutes
  namespace: argocd
spec:
  project: data-pipeline
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  source:
    repoURL: https://github.com/fabian-amrc/data-pipeline-application.git
    targetRevision: main
    path: traefik/ingressroutes
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
